name: trail
description: trail-game

publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.3
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.3
  flutter_svg: ^1.1.0
  flutter_native_splash: ^2.2.3+1
  audioplayers: ^1.0.1
  shared_preferences: ^2.0.15
  google_mobile_ads: ^1.3.0

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/launcher/icon.png'

flutter:
  assets:
    - assets/
    - assets/icons/
    - assets/levels/levels.json
    - assets/sounds/
  fonts:
    - family: 'Overpass'
      fonts:
        - asset: 'assets\fonts\Overpass-Regular.ttf'
  uses-material-design: true

flutter_native_splash:
  color: "#eeeeee"
  image: assets/launcher/icon.png
  ios: true
  android: true